# Model arguments
model_name_or_path: kevin1010607/llama2-7b-mod
tokenizer_name_or_path: meta-llama/Llama-2-7b-hf
model_revision: main
torch_dtype: float16
use_flash_attention_2: false

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
truncation_side: right
dataset_mixer:
  HuggingFaceH4/ultrachat_200k: 1.0
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
  - train_sft
  - test_sft
preprocessing_num_workers: 16

# SFT trainer config
bf16: false
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: kevin1010607/llama2-7b-mod-sft-full-2
hub_strategy: every_save
hub_private_repo: true
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: model/llama2-7b-mod-sft-full-2
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "epoch"
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
