# Model arguments
model_name_or_path: kevin1010607/llama2-7b-mod-sft-full-3
tokenizer_name_or_path: meta-llama/Llama-2-7b-hf
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
  HuggingFaceH4/cai-conversation-harmless: 1.0
  HuggingFaceH4/orca_dpo_pairs: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 16

# DPOTrainer arguments
bf16: false
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: kevin1010607/llama2-7b-mod-sft-full-dpo-full
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 512
num_train_epochs: 1
optim: adamw_torch
output_dir: model/llama2-7b-mod-sft-full-dpo-full
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: true
report_to:
  - tensorboard
  - wandb
save_strategy: "epoch"
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
